export interface ToolParam {
  name: string;
  label: string;
  type: 'text' | 'select' | 'number' | 'password' | 'color';
  options?: { value: string; label: string }[];
  defaultValue?: string | number;
  placeholder?: string;
}

export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  bgColor: string;
  borderColor: string;
  category: string;
  apiEndpoint: string;
  multipleFiles: boolean;
  /** Minimum number of files required when multipleFiles=true. Defaults to 2. */
  minFiles?: number;
  fileOptional?: boolean;
  inputLabel: string;
  acceptedFormats: string;
  outputFormat: string;
  outputMime: string;
  params?: ToolParam[];
  /** When set, ToolClient shows the PDF page as an interactive canvas.
   *  'point' = click to set x,y  |  'area' = drag to set x,y,width,height */
  pdfPositionMode?: 'point' | 'area';
  /** SEO overrides — if omitted the tool name/description are used as fallbacks */
  seoTitle?: string;
  seoDescription?: string;
}

export const CATEGORIES = [
  // ── PDF Categories ──────────────────────────────────────────────────────
  { id: 'organize',    label: 'Merge, Split & Organize',   color: '#3b82f6', icon: '🔀' },
  // { id: 'optimize',    label: 'Document Optimization',     color: '#06b6d4', icon: '⚡' },
  { id: 'to-pdf',      label: 'Convert TO PDF',            color: '#22c55e', icon: '⬆️' },
  { id: 'from-pdf',    label: 'Convert FROM PDF',          color: '#16a34a', icon: '⬇️' },
  { id: 'edit',        label: 'PDF Content Editing',       color: '#f97316', icon: '✏️' },
  { id: 'security',    label: 'Security & Sign',           color: '#ef4444', icon: '🔒' },
  { id: 'forms',       label: 'Interactive Forms',         color: '#7c3aed', icon: '📋' },
  { id: 'standards',   label: 'Technical Standards',       color: '#eab308', icon: '🏅' },
  // ── Image Categories ─────────────────────────────────────────────────────
  { id: 'img-convert', label: 'Digital Image Conversions', color: '#8b5cf6', icon: '🖼️' },
  { id: 'img-size',    label: 'Sizing & Dimensions',       color: '#14b8a6', icon: '📐' },
  { id: 'img-enhance', label: 'Image Enhancements',        color: '#f59e0b', icon: '✨' },
  { id: 'img-effects', label: 'Visual Effects',            color: '#ec4899', icon: '🎨' },
  { id: 'img-edit',    label: 'Image Content Editing',     color: '#6366f1', icon: '🖌️' },
];

export const TOOLS: Tool[] = [
  // ─── Merge, Split & Organize ───────────────────────────────────────────────
  {
    slug: 'merge/pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one single document',
    icon: '🔀',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/merge',
    multipleFiles: true,
    inputLabel: 'Select PDF files to merge',
    acceptedFormats: '.pdf',
    outputFormat: 'merged.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free PDF Merge Tool | Combine PDFs Online',
    seoDescription: 'Use our free merge tool to combine multiple PDFs into one file instantly. Fast, easy, and 100% online — no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'split-pdf',
    name: 'Split PDF',
    description: 'Split a PDF into separate pages or page ranges',
    icon: '✂️',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/split',
    multipleFiles: false,
    inputLabel: 'Select PDF to split',
    acceptedFormats: '.pdf',
    outputFormat: 'split.zip',
    outputMime: 'application/zip',
    params: [
      {
        name: 'split_mode',
        label: 'Split Mode',
        type: 'select',
        options: [
          { value: 'ranges', label: 'By Page Ranges' },
          { value: 'fixed_range', label: 'Every N Pages' },
          { value: 'remove_pages', label: 'Remove Pages' },
        ],
        defaultValue: 'ranges',
      },
      { name: 'ranges', label: 'Page Ranges (e.g. 1-3, 5)', type: 'text', defaultValue: '1-999', placeholder: '1-3, 5' },
      { name: 'fixed_range', label: 'Pages per split', type: 'number', defaultValue: 1 },
    ],
    seoTitle: 'Free PDF Split Tool | Split PDFs Online',
    seoDescription: 'Use our free PDF split tool to split PDF files into pages instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'selective-merge',
    name: 'Selective Page Merge',
    description: 'Merge only specific pages from different PDF documents into one',
    icon: '📑',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/selective-merge',
    multipleFiles: true,
    inputLabel: 'Select PDF files to merge selectively',
    acceptedFormats: '.pdf',
    outputFormat: 'merged.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'page_ranges', label: 'Page Ranges per File — use | to separate files (e.g. 1-3 | 2,4 | 1)', type: 'text', defaultValue: '', placeholder: '1-3 | 2,4 | 1' },
    ],
    seoTitle: 'Free Selective PDF Merge Tool | Merge Pages Online',
    seoDescription: 'Use our free selective merge tool to combine selected PDF pages instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  {
    slug: 'split-by-size',
    name: 'Split PDF by Size',
    description: 'Divide a large PDF into smaller files based on a target file size',
    icon: '📦',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/split-by-size',
    multipleFiles: false,
    inputLabel: 'Select PDF to split by size',
    acceptedFormats: '.pdf',
    outputFormat: 'split.zip',
    outputMime: 'application/zip',
    params: [
      { name: 'max_size_mb', label: 'Max Size per File (MB)', type: 'number', defaultValue: 5 },
    ],
    seoTitle: 'Free PDF Split by Size Tool | Split PDFs Online',
    seoDescription: 'Use our free split by size tool to divide large PDFs into smaller files instantly. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'split-by-bookmark',
    name: 'Split PDF by Bookmark',
    description: 'Separate a PDF into multiple files using its internal bookmarks or chapters',
    icon: '🔖',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/split-by-bookmark',
    multipleFiles: false,
    inputLabel: 'Select PDF to split by bookmark',
    acceptedFormats: '.pdf',
    outputFormat: 'split.zip',
    outputMime: 'application/zip',
    params: [
      {
        name: 'bookmark_level',
        label: 'Bookmark Level',
        type: 'select',
        options: [
          { value: '1', label: 'Level 1 (Top-level chapters)' },
          { value: '2', label: 'Level 2 (Sub-sections)' },
          { value: 'all', label: 'All Levels' },
        ],
        defaultValue: '1',
      },
    ],
    seoTitle: 'Free Split PDF by Bookmark Tool | Split Online',
    seoDescription: 'Use our free split PDF by bookmark tool to divide PDFs instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'delete-pages',
    name: 'Delete Pages',
    description: 'Remove unwanted pages from a PDF document',
    icon: '🗑️',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/delete-pages',
    multipleFiles: false,
    inputLabel: 'Select PDF to delete pages from',
    acceptedFormats: '.pdf',
    outputFormat: 'output.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'pages', label: 'Pages to Delete (e.g. 2, 4-6)', type: 'text', defaultValue: '', placeholder: '2, 4-6' },
    ],
    seoTitle: 'Free Delete PDF Pages Tool | Remove Pages Online',
    seoDescription: 'Use our free delete pages tool to remove pages from PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'rotate-pages',
    name: 'Rotate Pages',
    description: 'Change the orientation of specific pages within a PDF',
    icon: '↩️',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/rotate-pages',
    multipleFiles: false,
    inputLabel: 'Select PDF to rotate pages',
    acceptedFormats: '.pdf',
    outputFormat: 'rotated.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'pages', label: 'Pages to Rotate (e.g. 1, 3-5 or "all")', type: 'text', defaultValue: 'all', placeholder: '1, 3-5' },
      {
        name: 'rotation',
        label: 'Rotation Degrees',
        type: 'select',
        options: [
          { value: '90',  label: '90° Clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '270° Counter-clockwise' },
        ],
        defaultValue: '90',
      },
    ],
    seoTitle: 'Free Rotate PDF Pages Tool | Rotate Pages Online',
    seoDescription: 'Use our free rotate pages tool to rotate PDF pages instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'reorder-pages',
    name: 'Reorder Pages',
    description: 'Change the sequence of pages within a PDF document',
    icon: '🔃',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/reorder-pages',
    multipleFiles: false,
    inputLabel: 'Select PDF to reorder pages',
    acceptedFormats: '.pdf',
    outputFormat: 'reordered.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'order', label: 'New Page Order (e.g. 3, 1, 2, 4)', type: 'text', defaultValue: '', placeholder: '3, 1, 2, 4' },
    ],
    seoTitle: 'Free PDF Reorder Pages Tool | Rearrange PDF Pages Online',
    seoDescription: 'Use our free reorder pages tool to rearrange PDF pages instantly online. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'extract-pages',
    name: 'Extract Pages',
    description: 'Pull out selected pages from a PDF into a new document',
    icon: '📤',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/extract-pages',
    multipleFiles: false,
    inputLabel: 'Select PDF to extract pages from',
    acceptedFormats: '.pdf',
    outputFormat: 'extracted.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'pages', label: 'Pages to Extract (e.g. 1-3, 5)', type: 'text', defaultValue: '', placeholder: '1-3, 5' },
    ],
    seoTitle: 'Free Extract PDF Pages Tool | Split Pages Online',
    seoDescription: 'Use our free extract pages tool to extract PDF pages instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'reverse-pages',
    name: 'Reverse Page Order',
    description: 'Flip the sequence of the entire PDF document from back to front',
    icon: '🔁',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/reverse-pages',
    multipleFiles: false,
    inputLabel: 'Select PDF to reverse',
    acceptedFormats: '.pdf',
    outputFormat: 'reversed.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free Reverse PDF Pages Tool | Change Page Order Online',
    seoDescription: 'Use our free reverse pages tool to instantly change the order of PDF pages online. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Reorder, remove or rearrange pages in your PDF document',
    icon: '🗂️',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/organize-pdf',
    multipleFiles: false,
    inputLabel: 'Select PDF to organize',
    acceptedFormats: '.pdf',
    outputFormat: 'organized.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'pages', label: 'Page Order (e.g. 3,1,2 or 1-3,5)', type: 'text', defaultValue: '', placeholder: '3,1,2 or 1-3,5' },
    ],
    seoTitle: 'Free PDF Organizer Tool | Organize PDFs Online',
    seoDescription: 'Free PDF Organizer Tool lets you organize PDFs easily. Free PDF Organizer Tool helps you rearrange, merge, sort and organize pages online instantly.',
  },
  {
    slug: 'translate-pdf',
    name: 'Translate PDF',
    description: 'Translate PDF text content into another language',
    icon: '🌐',
    color: '#3b82f6',
    bgColor: '#eff6ff',
    borderColor: '#bfdbfe',
    category: 'organize',
    apiEndpoint: '/pdf/translate-pdf',
    multipleFiles: false,
    inputLabel: 'Select PDF to translate',
    acceptedFormats: '.pdf',
    outputFormat: 'translated.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'target_lang',
        label: 'Target Language',
        type: 'select',
        defaultValue: 'es',
        options: [
          { value: 'es', label: 'Spanish' },
          { value: 'fr', label: 'French' },
          { value: 'de', label: 'German' },
          { value: 'it', label: 'Italian' },
          { value: 'pt', label: 'Portuguese' },
          { value: 'ru', label: 'Russian' },
          { value: 'zh-CN', label: 'Chinese (Simplified)' },
          { value: 'ja', label: 'Japanese' },
          { value: 'ar', label: 'Arabic' },
          { value: 'hi', label: 'Hindi' },
          { value: 'ko', label: 'Korean' },
          { value: 'nl', label: 'Dutch' },
          { value: 'tr', label: 'Turkish' },
          { value: 'pl', label: 'Polish' },
          { value: 'sv', label: 'Swedish' },
          { value: 'en', label: 'English' },
        ],
      },
    ],
    seoTitle: 'Free Translate PDF Tool | Translate PDF Online',
    seoDescription: 'Use our free translate PDF tool to translate PDF files instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  // ─── Document Optimization ────────────────────────────────────────────────
  {
    slug: 'compress',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality',
    icon: '🗜️',
    color: '#06b6d4',
    bgColor: '#ecfeff',
    borderColor: '#a5f3fc',
    category: 'optimize',
    apiEndpoint: '/pdf/compress',
    multipleFiles: false,
    inputLabel: 'Select PDF to compress',
    acceptedFormats: '.pdf',
    outputFormat: 'compressed.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'compression_level',
        label: 'Compression Level',
        type: 'select',
        options: [
          { value: 'low', label: 'Low (better quality)' },
          { value: 'recommended', label: 'Recommended (balanced)' },
          { value: 'extreme', label: 'Extreme (smallest size)' },
        ],
        defaultValue: 'recommended',
      },
    ],
    seoTitle: 'Free PDF Compress Tool | Reduce PDF Size Online',
    seoDescription: 'Use our free PDF compress tool to reduce file size instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'rotate',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to the correct orientation',
    icon: '🔄',
    color: '#06b6d4',
    bgColor: '#ecfeff',
    borderColor: '#a5f3fc',
    category: 'optimize',
    apiEndpoint: '/pdf/rotate',
    multipleFiles: false,
    inputLabel: 'Select PDF to rotate',
    acceptedFormats: '.pdf',
    outputFormat: 'rotated.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'rotation',
        label: 'Rotation Degrees',
        type: 'select',
        options: [
          { value: '90',  label: '90° Clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '270° (90° Counter-clockwise)' },
        ],
        defaultValue: '90',
      },
    ],
    seoTitle: 'Free Image Rotate Tool | Rotate Images Online',
    seoDescription: 'Use our free image rotate tool to rotate images instantly in any direction. Fast, easy, and 100% online — no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'repair',
    name: 'Repair PDF',
    description: 'Fix corrupted or damaged PDF files',
    icon: '🔧',
    color: '#06b6d4',
    bgColor: '#ecfeff',
    borderColor: '#a5f3fc',
    category: 'optimize',
    apiEndpoint: '/pdf/repair',
    multipleFiles: false,
    inputLabel: 'Select PDF to repair',
    acceptedFormats: '.pdf',
    outputFormat: 'repaired.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free PDF Repair Tool | Fix Corrupted PDFs Online',
    seoDescription: 'Use our free PDF repair tool to fix corrupted or damaged PDF files instantly. Fast, easy, and 100% online — no installation needed.',
  },
  // ─── Convert TO PDF ────────────────────────────────────────────────────────
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents (DOCX/DOC) to PDF format',
    icon: '📝',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/office-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select Word document',
    acceptedFormats: '.doc,.docx',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free Word to PDF Tool | Convert DOC to PDF Online',
    seoDescription: 'Use our free Word to PDF tool to convert DOC files into PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets (XLSX/XLS) to PDF format',
    icon: '📊',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/office-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select Excel file',
    acceptedFormats: '.xls,.xlsx',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free Excel to PDF Tool | Convert Excel to PDF Online',
    seoDescription: 'Free Excel to PDF Tool lets you convert Excel files to PDF instantly. Use Free Excel to PDF Tool to convert XLS/XLSX files online quickly and easily.',
  },
  {
    slug: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations (PPTX/PPT) to PDF',
    icon: '📋',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/office-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select PowerPoint file',
    acceptedFormats: '.ppt,.pptx',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free PPT to PDF Tool | Convert PowerPoint Online',
    seoDescription: 'Use our free PPT to PDF tool to convert PowerPoint files to PDF instantly. Fast, easy, and 100% online — no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert JPG, PNG, TIFF images to PDF format',
    icon: '🖼️',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/image-to-pdf',
    multipleFiles: true,
    minFiles: 1,
    inputLabel: 'Select images',
    acceptedFormats: '.jpg,.jpeg,.png,.tiff,.bmp,.gif',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free Image to PDF Tool | Convert Images Online',
    seoDescription: 'Use our free image to PDF tool to convert JPG, PNG images into PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  {
    slug: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert HTML files or web pages to PDF format',
    icon: '🌐',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/html-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select HTML file',
    acceptedFormats: '.html,.htm',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free HTML to PDF Tool | Convert Web Pages Online',
    seoDescription: 'Use our free HTML to PDF tool to convert web pages into PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'rtf-to-pdf',
    name: 'RTF to PDF',
    description: 'Convert Rich Text Format (RTF) documents to PDF',
    icon: '📄',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/office-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select RTF document',
    acceptedFormats: '.rtf',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free RTF to PDF Tool | Convert RTF Online',
    seoDescription: 'Use our free RTF to PDF tool to convert RTF files into PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'epub-to-pdf',
    name: 'EPUB to PDF',
    description: 'Convert EPUB eBooks to PDF format',
    icon: '📚',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/epub-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select EPUB file',
    acceptedFormats: '.epub',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free EPUB to PDF Tool | Convert EPUB Online',
    seoDescription: 'Use our free EPUB to PDF tool to convert EPUB files into PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'cad-to-pdf',
    name: 'CAD to PDF',
    description: 'Convert CAD drawings (DXF, DWG, DWF) to PDF format',
    icon: '📐',
    color: '#22c55e',
    bgColor: '#f0fdf4',
    borderColor: '#bbf7d0',
    category: 'to-pdf',
    apiEndpoint: '/pdf/cad-to-pdf',
    multipleFiles: false,
    inputLabel: 'Select CAD file (DXF, DWG or DWF)',
    acceptedFormats: '.dxf,.dwg,.dwf',
    outputFormat: 'converted.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free CAD to PDF Tool | Convert CAD Online',
    seoDescription: 'Use our free CAD to PDF tool to convert CAD files into PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  // ─── Convert FROM PDF ──────────────────────────────────────────────────────
  {
    slug: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert each PDF page to a JPG or PNG image (single page returned directly, multi-page as ZIP)',
    icon: '🖼️',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-image',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'images.zip',
    outputMime: 'application/zip',
    params: [
      {
        name: 'format',
        label: 'Image format',
        type: 'select',
        options: [
          { value: 'jpg', label: 'JPEG (smaller file)' },
          { value: 'png', label: 'PNG (lossless)' },
        ],
        defaultValue: 'jpg',
      },
      {
        name: 'dpi',
        label: 'Resolution (DPI)',
        type: 'select',
        options: [
          { value: '96',  label: '96 DPI  – screen' },
          { value: '150', label: '150 DPI – standard' },
          { value: '300', label: '300 DPI – print quality' },
        ],
        defaultValue: '150',
      },
    ],
    seoTitle: 'Free PDF to Image Converter | Convert PDF to JPG/PNG Online',
    seoDescription: 'Use our free PDF to image tool to convert PDF pages into JPG or PNG instantly. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'extract',
    name: 'Extract Pages',
    description: 'Extract pages or images from a PDF as a ZIP archive',
    icon: '📤',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/extract',
    multipleFiles: false,
    inputLabel: 'Select PDF to extract from',
    acceptedFormats: '.pdf',
    outputFormat: 'extracted.zip',
    outputMime: 'application/zip',
    params: [
      {
        name: 'mode',
        label: 'Extract Mode',
        type: 'select',
        options: [
          { value: 'pages', label: 'Extract as individual PDF pages' },
          { value: 'images', label: 'Extract embedded images' },
        ],
        defaultValue: 'pages',
      },
    ],
    seoTitle: 'Free PDF Extract Tool | Extract Pages Online',
    seoDescription: 'Use our free PDF extract tool to extract pages from PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract plain text content from a PDF document',
    icon: '🔤',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-text',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted.txt',
    outputMime: 'text/plain',
    seoTitle: 'Free PDF to Text Tool | Extract Text Online',
    seoDescription: 'Use our free PDF to text tool to extract text from PDF files instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  {
    slug: 'pdf-to-epub',
    name: 'PDF to EPUB',
    description: 'Convert PDF documents to EPUB eBook format',
    icon: '📚',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-epub',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted.epub',
    outputMime: 'application/epub+zip',
    seoTitle: 'Free PDF to EPUB Tool | Convert PDF Online',
    seoDescription: 'Use our free PDF to EPUB tool to convert PDF files into EPUB format instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  {
    slug: 'pdf-to-html',
    name: 'PDF to HTML',
    description: 'Convert PDF documents to HTML web pages',
    icon: '🌐',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-html',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted.html',
    outputMime: 'text/html',
    seoTitle: 'Free PDF to HTML Tool | Convert PDF Online',
    seoDescription: 'Use our free PDF to HTML tool to convert PDF files into HTML instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  {
    slug: 'pdf-to-csv',
    name: 'PDF to CSV',
    description: 'Extract tabular data from PDF and export as CSV',
    icon: '📑',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-csv',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted.csv',
    outputMime: 'text/csv',
    seoTitle: 'Free PDF to CSV Converter | Extract Data from PDF to CSV Online',
    seoDescription: 'Use our free PDF to CSV tool to convert PDF files into editable CSV format instantly. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'pdf-to-xml',
    name: 'PDF to XML',
    description: 'Convert PDF data and structure to XML format',
    icon: '🗂️',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-xml',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted.xml',
    outputMime: 'application/xml',
    seoTitle: 'Free PDF to XML Tool | Convert PDF Online',
    seoDescription: 'Use our free PDF to XML tool to convert PDF files into XML instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF documents to editable Word DOCX format',
    icon: '📝',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-word',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted.docx',
    outputMime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    seoTitle: 'Free PDF to Word Converter | Convert PDF to DOCX Online',
    seoDescription: 'Use our free PDF to Word tool to convert PDF files into editable Word documents instantly. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF tables and data to Excel XLSX spreadsheet',
    icon: '📊',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-excel',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted.xlsx',
    outputMime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    seoTitle: 'Free PDF to Excel Tool | Convert PDF Online',
    seoDescription: 'Use our free PDF to Excel tool to convert PDF files into Excel instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  {
    slug: 'pdf-to-pptx',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF pages to editable PowerPoint PPTX slides',
    icon: '📽️',
    color: '#16a34a',
    bgColor: '#f0fdf4',
    borderColor: '#86efac',
    category: 'from-pdf',
    apiEndpoint: '/pdf/pdf-to-pptx',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'presentation.pptx',
    outputMime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    seoTitle: 'Free PDF to PPTX Converter | Convert PDF to PowerPoint Online',
    seoDescription: 'Use our free PDF to PPTX tool to convert PDF files into PowerPoint slides instantly. Fast, easy, and 100% online — no installation needed.',
  },
  // ─── Content Editing ───────────────────────────────────────────────────────
  {
    slug: 'watermark',
    name: 'Add Watermark',
    description: 'Add text watermark to PDF pages',
    icon: '💧',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/watermark',
    multipleFiles: false,
    inputLabel: 'Select PDF to watermark',
    acceptedFormats: '.pdf',
    outputFormat: 'watermarked.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'text', label: 'Watermark Text', type: 'text', defaultValue: 'CONFIDENTIAL', placeholder: 'Enter watermark text' },
      {
        name: 'vertical_position',
        label: 'Vertical Position',
        type: 'select',
        options: [
          { value: 'top', label: 'Top' },
          { value: 'middle', label: 'Middle' },
          { value: 'bottom', label: 'Bottom' },
        ],
        defaultValue: 'middle',
      },
      {
        name: 'horizontal_position',
        label: 'Horizontal Position',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'center',
      },
      { name: 'font_size', label: 'Font Size', type: 'number', defaultValue: 40 },
      { name: 'transparency', label: 'Transparency (0-100)', type: 'number', defaultValue: 50 },
      { name: 'rotation', label: 'Rotation (degrees, 0–360)', type: 'number', defaultValue: 315 },
      { name: 'font_color', label: 'Color', type: 'color', defaultValue: '#FF0000' },
    ],
    seoTitle: 'Free Watermark Tool | Add Logo Online',
    seoDescription: 'Use our free watermark tool to add text or logo to images instantly online. Fast, easy, and 100% free—no installation required. Try GoDocLab! today',
  },
  {
    slug: 'pdf-remove-watermark',
    name: 'Remove Watermark',
    description: 'Remove text or image watermarks from PDF pages',
    icon: '🧹',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/remove-watermark',
    multipleFiles: false,
    inputLabel: 'Select PDF to clean',
    acceptedFormats: '.pdf',
    outputFormat: 'cleaned.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'strength',
        label: 'Removal Strength',
        type: 'select',
        options: [
          { value: '30', label: 'Light (30%) — subtle watermarks' },
          { value: '60', label: 'Medium (60%) — standard watermarks' },
          { value: '85', label: 'Strong (85%) — heavy watermarks' },
        ],
        defaultValue: '60',
      },
    ],
    seoTitle: 'Free PDF Remove Watermark Tool | Clean PDFs Online',
    seoDescription: 'Use our free PDF remove watermark tool to erase text and image watermarks from PDFs instantly online. Fast, easy, and 100% free—no installation needed.',
  },
  {
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    description: 'Insert page numbers into your PDF document',
    icon: '#️⃣',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/page-numbers',
    multipleFiles: false,
    inputLabel: 'Select PDF to number',
    acceptedFormats: '.pdf',
    outputFormat: 'numbered.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'starting_number', label: 'Starting Number', type: 'number', defaultValue: 1 },
      {
        name: 'vertical_position',
        label: 'Position (Vertical)',
        type: 'select',
        options: [
          { value: 'top', label: 'Top' },
          { value: 'bottom', label: 'Bottom' },
        ],
        defaultValue: 'bottom',
      },
      {
        name: 'horizontal_position',
        label: 'Position (Horizontal)',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'center',
      },
      { name: 'font_size', label: 'Font Size', type: 'number', defaultValue: 12 },
      { name: 'font_color', label: 'Color', type: 'color', defaultValue: '#000000' },
    ],
    seoTitle: 'Free Page Numbers Tool | Add Page Numbers Online',
    seoDescription: 'Use our free page numbers tool to add page numbers to PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'ocr',
    name: 'OCR PDF',
    description: 'Make scanned PDFs searchable with Optical Character Recognition',
    icon: '🔍',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/ocr',
    multipleFiles: false,
    inputLabel: 'Select scanned PDF',
    acceptedFormats: '.pdf',
    outputFormat: 'pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'language',
        label: 'Document Language',
        type: 'select',
        options: [
          { value: 'eng', label: 'English' },
          { value: 'spa', label: 'Spanish' },
          { value: 'fra', label: 'French' },
          { value: 'deu', label: 'German' },
          { value: 'por', label: 'Portuguese' },
          { value: 'ita', label: 'Italian' },
          { value: 'chi_sim', label: 'Chinese (Simplified)' },
          { value: 'ara', label: 'Arabic' },
        ],
        defaultValue: 'eng',
      },
    ],
    seoTitle: 'Free OCR Tool | Extract Text from Image Online',
    seoDescription: 'Use our free OCR tool to extract text from images and scanned PDFs instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  // ─── Content Editing — Annotate & Comment ────────────────────────────────
  {
    slug: 'add-text-box',
    name: 'Add Text Box',
    description: 'Add a custom text box anywhere on your PDF pages',
    icon: '🖊️',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/add-text-box',
    multipleFiles: false,
    inputLabel: 'Select PDF to add text',
    acceptedFormats: '.pdf',
    outputFormat: 'edited.pdf',
    outputMime: 'application/pdf',
    pdfPositionMode: 'point',
    params: [
      { name: 'text', label: 'Text Content', type: 'text', defaultValue: 'Your text here', placeholder: 'Enter text to add' },
      { name: 'pages', label: 'Page (e.g. 1)', type: 'text', defaultValue: '1', placeholder: '1' },
      { name: 'x', label: 'X Position (px)', type: 'number', defaultValue: 100 },
      { name: 'y', label: 'Y Position (px)', type: 'number', defaultValue: 100 },
      { name: 'font_size', label: 'Font Size', type: 'number', defaultValue: 14 },
      { name: 'font_color', label: 'Text Color', type: 'color', defaultValue: '#000000' },
      { name: 'opacity', label: 'Opacity (0–100)', type: 'number', defaultValue: 100 },
      { name: 'rotation', label: 'Rotation (degrees)', type: 'number', defaultValue: 0 },
    ],
    seoTitle: 'Free Add Text Box Tool | Insert Text Online',
    seoDescription: 'Use our free add text box tool to insert text into images or PDFs instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  {
    slug: 'sticky-note',
    name: 'Sticky Note',
    description: 'Attach a sticky note annotation to a PDF page',
    icon: '🗒️',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/sticky-note',
    multipleFiles: false,
    inputLabel: 'Select PDF to annotate',
    acceptedFormats: '.pdf',
    outputFormat: 'annotated.pdf',
    outputMime: 'application/pdf',
    pdfPositionMode: 'point',
    params: [
      { name: 'text', label: 'Note Text', type: 'text', defaultValue: 'Note here', placeholder: 'Enter note content' },
      { name: 'pages', label: 'Page Number', type: 'number', defaultValue: 1 },
      { name: 'x', label: 'X Position (px)', type: 'number', defaultValue: 100 },
      { name: 'y', label: 'Y Position (px)', type: 'number', defaultValue: 100 },
    ],
    seoTitle: 'Free Sticky Note Tool | Add Notes Online',
    seoDescription: 'Use our free sticky note tool to create and manage notes instantly online. Fast, easy, and 100% web-based - no installation needed. Try GoDocLab!',
  },
  {
    slug: 'highlight',
    name: 'Highlight Text',
    description: 'Add a highlight annotation over a specific area of a PDF',
    icon: '🖍️',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/highlight',
    multipleFiles: false,
    inputLabel: 'Select PDF to highlight',
    acceptedFormats: '.pdf',
    outputFormat: 'highlighted.pdf',
    outputMime: 'application/pdf',
    pdfPositionMode: 'area',
    params: [
      { name: 'pages', label: 'Page Number', type: 'number', defaultValue: 1 },
      { name: 'x', label: 'X Position (px)', type: 'number', defaultValue: 100 },
      { name: 'y', label: 'Y Position (px)', type: 'number', defaultValue: 100 },
      { name: 'width', label: 'Width (px)', type: 'number', defaultValue: 200 },
      { name: 'height', label: 'Height (px)', type: 'number', defaultValue: 20 },
      { name: 'color', label: 'Highlight Color', type: 'color', defaultValue: '#FFFF00' },
    ],
    seoTitle: 'Free Highlight PDF Tool | Highlight Text Online',
    seoDescription: 'Use our free highlight tool to highlight text in PDFs instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'underline',
    name: 'Underline Text',
    description: 'Add an underline annotation to a specific area of a PDF',
    icon: '📏',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/underline',
    multipleFiles: false,
    inputLabel: 'Select PDF to underline',
    acceptedFormats: '.pdf',
    outputFormat: 'underlined.pdf',
    outputMime: 'application/pdf',
    pdfPositionMode: 'area',
    params: [
      { name: 'pages', label: 'Page Number', type: 'number', defaultValue: 1 },
      { name: 'x', label: 'X Position (px)', type: 'number', defaultValue: 100 },
      { name: 'y', label: 'Y Position (px)', type: 'number', defaultValue: 100 },
      { name: 'width', label: 'Width (px)', type: 'number', defaultValue: 200 },
      { name: 'height', label: 'Height (px)', type: 'number', defaultValue: 20 },
    ],
    seoTitle: 'Free Text Underline Tool | Underline Text Online',
    seoDescription: 'Use our free underline tool to underline text instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'strikeout',
    name: 'Strikeout',
    description: 'Add a strikeout annotation over a specific area of a PDF',
    icon: '✒️',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/strikeout',
    multipleFiles: false,
    inputLabel: 'Select PDF to strikeout',
    acceptedFormats: '.pdf',
    outputFormat: 'strikeout.pdf',
    outputMime: 'application/pdf',
    pdfPositionMode: 'area',
    params: [
      { name: 'pages', label: 'Page Number', type: 'number', defaultValue: 1 },
      { name: 'x', label: 'X Position (px)', type: 'number', defaultValue: 100 },
      { name: 'y', label: 'Y Position (px)', type: 'number', defaultValue: 100 },
      { name: 'width', label: 'Width (px)', type: 'number', defaultValue: 200 },
      { name: 'height', label: 'Height (px)', type: 'number', defaultValue: 20 },
    ],
    seoTitle: 'Free PDF Strikeout Tool | Add Strikethrough Online',
    seoDescription: 'Use our free PDF strikeout tool to add strikethrough text instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  // ─── Watermarks & Numbering (additional) ─────────────────────────────────
  // {
  //   slug: 'image-watermark',
  //   name: 'Image Watermark',
  //   description: 'Stamp a custom image as a watermark onto your PDF pages',
  //   icon: '🌊',
  //   color: '#f97316',
  //   bgColor: '#fff7ed',
  //   borderColor: '#fed7aa',
  //   category: 'edit',
  //   apiEndpoint: '/pdf/image-watermark',
  //   multipleFiles: false,
  //   inputLabel: 'Select PDF to watermark',
  //   acceptedFormats: '.pdf',
  //   outputFormat: 'watermarked.pdf',
  //   outputMime: 'application/pdf',
  //   params: [
  //     { name: 'image_url', label: 'Watermark Image URL', type: 'text', defaultValue: '', placeholder: 'https://example.com/logo.png' },
  //     {
  //       name: 'gravity',
  //       label: 'Position',
  //       type: 'select',
  //       options: [
  //         { value: 'Center', label: 'Center' },
  //         { value: 'North', label: 'Top Center' },
  //         { value: 'South', label: 'Bottom Center' },
  //         { value: 'NorthEast', label: 'Top Right' },
  //         { value: 'NorthWest', label: 'Top Left' },
  //         { value: 'SouthEast', label: 'Bottom Right' },
  //         { value: 'SouthWest', label: 'Bottom Left' },
  //       ],
  //       defaultValue: 'Center',
  //     },
  //     { name: 'opacity', label: 'Opacity (0–100)', type: 'number', defaultValue: 50 },
  //     { name: 'scale', label: 'Scale (%)', type: 'number', defaultValue: 50 },
  //     { name: 'rotation', label: 'Rotation (degrees)', type: 'number', defaultValue: 0 },
  //     { name: 'pages', label: 'Pages (all or e.g. 1-3)', type: 'text', defaultValue: 'all' },
  //   ],
  // },
  {
    slug: 'bates-numbering',
    name: 'Bates Numbering',
    description: 'Add Bates numbers with prefix/suffix to PDF pages for legal documents',
    icon: '🔢',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/bates-numbering',
    multipleFiles: false,
    inputLabel: 'Select PDF for Bates numbering',
    acceptedFormats: '.pdf',
    outputFormat: 'bates.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'prefix', label: 'Prefix (e.g. DOC-)', type: 'text', defaultValue: 'DOC-', placeholder: 'DOC-' },
      { name: 'suffix', label: 'Suffix (optional)', type: 'text', defaultValue: '', placeholder: '' },
      { name: 'starting_number', label: 'Starting Number', type: 'number', defaultValue: 1 },
      {
        name: 'vertical_position',
        label: 'Vertical Position',
        type: 'select',
        options: [
          { value: 'top', label: 'Top' },
          { value: 'bottom', label: 'Bottom' },
        ],
        defaultValue: 'bottom',
      },
      {
        name: 'horizontal_position',
        label: 'Horizontal Position',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'right',
      },
      { name: 'font_size', label: 'Font Size', type: 'number', defaultValue: 12 },
      { name: 'font_color', label: 'Color', type: 'color', defaultValue: '#000000' },
    ],
    seoTitle: 'Free Bates Numbering Tool | Add Legal Page Numbers to PDFs',
    seoDescription: 'Use our free Bates numbering tool to add legal page numbers to PDFs instantly. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, images, and annotations anywhere on your PDF pages',
    icon: '📝',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/edit-pdf',
    multipleFiles: false,
    inputLabel: 'Select PDF to edit',
    acceptedFormats: '.pdf',
    outputFormat: 'edited.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'text', label: 'Text to Add', type: 'text', defaultValue: '', placeholder: 'Enter text to insert' },
      { name: 'pages', label: 'Page Number', type: 'text', defaultValue: '1', placeholder: '1' },
      { name: 'x', label: 'X Position (px)', type: 'number', defaultValue: 100 },
      { name: 'y', label: 'Y Position (px)', type: 'number', defaultValue: 100 },
      { name: 'font_size', label: 'Font Size', type: 'number', defaultValue: 14 },
      { name: 'font_color', label: 'Text Color', type: 'color', defaultValue: '#000000' },
      { name: 'opacity', label: 'Opacity (0–100)', type: 'number', defaultValue: 100 },
      { name: 'rotation', label: 'Rotation (degrees)', type: 'number', defaultValue: 0 },
    ],
    seoTitle: 'Free Edit PDF Tool | Edit PDF Files Online',
    seoDescription: 'Use our free Edit PDF tool to add text, annotations and content to PDF files online. Fast, easy, and 100% free — no installation needed. Try GoDocLab!',
  },
  {
    slug: 'edit-text',
    name: 'Edit Text',
    description: 'Cover existing text with a background block and write replacement text at the same position',
    icon: '✏️',
    color: '#f97316',
    bgColor: '#fff7ed',
    borderColor: '#fed7aa',
    category: 'edit',
    apiEndpoint: '/pdf/edit-text',
    multipleFiles: false,
    inputLabel: 'Select PDF to edit text',
    acceptedFormats: '.pdf',
    outputFormat: 'edited.pdf',
    outputMime: 'application/pdf',
    pdfPositionMode: 'point',
    params: [
      { name: 'new_text', label: 'Replacement Text', type: 'text', defaultValue: '', placeholder: 'New text to write' },
      { name: 'page', label: 'Page Number', type: 'number', defaultValue: 1 },
      { name: 'x', label: 'X Position (px)', type: 'number', defaultValue: 100 },
      { name: 'y', label: 'Y Position (px)', type: 'number', defaultValue: 100 },
      { name: 'cover_width', label: 'Cover Width (px)', type: 'number', defaultValue: 200 },
      { name: 'cover_height', label: 'Cover Height (px)', type: 'number', defaultValue: 20 },
      { name: 'font_size', label: 'Font Size', type: 'number', defaultValue: 12 },
      { name: 'font_color', label: 'Text Color', type: 'color', defaultValue: '#000000' },
      { name: 'cover_color', label: 'Cover Background Color', type: 'color', defaultValue: '#ffffff' },
    ],
    seoTitle: 'Free Edit Text Tool | Edit Text Online',
    seoDescription: 'Use our free edit text tool to edit text instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  // ─── Security & Sign ───────────────────────────────────────────────────────
  {
    slug: 'protect',
    name: 'Protect PDF',
    description: 'Password protect your PDF to restrict access',
    icon: '🔐',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    category: 'security',
    apiEndpoint: '/pdf/protect',
    multipleFiles: false,
    inputLabel: 'Select PDF to protect',
    acceptedFormats: '.pdf',
    outputFormat: 'protected.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'password', label: 'Password', type: 'password', placeholder: 'Enter password', defaultValue: '' },
    ],
    seoTitle: 'Free PDF Protect Tool | Secure PDFs Online',
    seoDescription: 'Use our free PDF Protect tool to secure your PDF files with password protection instantly. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'unlock',
    name: 'Unlock PDF',
    description: 'Remove password protection from a PDF file',
    icon: '🔓',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    category: 'security',
    apiEndpoint: '/pdf/unlock',
    multipleFiles: false,
    inputLabel: 'Select protected PDF',
    acceptedFormats: '.pdf',
    outputFormat: 'unlocked.pdf',
    outputMime: 'application/pdf',
    params: [],
    seoTitle: 'Free PDF Unlock Tool | Remove PDF Password Online',
    seoDescription: 'Use our free PDF unlock tool to remove password from PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'set-permissions',
    name: 'Set Permissions',
    description: 'Set an owner password and restrict printing, editing, or copying content',
    icon: '🛡️',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    category: 'security',
    apiEndpoint: '/pdf/set-permissions',
    multipleFiles: false,
    inputLabel: 'Select PDF to restrict',
    acceptedFormats: '.pdf',
    outputFormat: 'restricted.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'owner_password', label: 'Owner Password', type: 'password', defaultValue: '', placeholder: 'Set owner password' },
      { name: 'user_password', label: 'User Password (optional open password)', type: 'password', defaultValue: '', placeholder: 'Optional' },
      {
        name: 'allow_printing',
        label: 'Allow Printing',
        type: 'select',
        options: [
          { value: 'none', label: 'Not Allowed' },
          { value: 'low', label: 'Low Resolution Only' },
          { value: 'high', label: 'High Resolution' },
        ],
        defaultValue: 'high',
      },
      {
        name: 'allow_editing',
        label: 'Allow Editing',
        type: 'select',
        options: [
          { value: 'true', label: 'Allowed' },
          { value: 'false', label: 'Not Allowed' },
        ],
        defaultValue: 'false',
      },
      {
        name: 'allow_copying',
        label: 'Allow Copying Content',
        type: 'select',
        options: [
          { value: 'true', label: 'Allowed' },
          { value: 'false', label: 'Not Allowed' },
        ],
        defaultValue: 'false',
      },
    ],
    seoTitle: 'Free Set Permissions Tool | Manage File Access Online',
    seoDescription: 'Use our free set permissions tool to manage file access instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'redact',
    name: 'Redact PDF',
    description: 'Permanently black out sensitive areas on specific PDF pages',
    icon: '⬛',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    category: 'security',
    apiEndpoint: '/pdf/redact',
    multipleFiles: false,
    inputLabel: 'Select PDF to redact',
    acceptedFormats: '.pdf',
    outputFormat: 'redacted.pdf',
    outputMime: 'application/pdf',
    pdfPositionMode: 'area',
    params: [
      { name: 'page', label: 'Page Number', type: 'number', defaultValue: 1 },
      { name: 'x', label: 'X Position (px)', type: 'number', defaultValue: 100 },
      { name: 'y', label: 'Y Position (px)', type: 'number', defaultValue: 100 },
      { name: 'width', label: 'Width (px)', type: 'number', defaultValue: 200 },
      { name: 'height', label: 'Height (px)', type: 'number', defaultValue: 20 },
      { name: 'color', label: 'Redaction Color', type: 'color', defaultValue: '#000000' },
    ],
    seoTitle: 'Free PDF Redact Tool | Hide Sensitive Data Online',
    seoDescription: 'Use our free PDF redact tool to hide or remove sensitive text instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'stamp',
    name: 'Add Stamp',
    description: 'Add a visual approval or e-sign stamp (e.g. APPROVED, DRAFT) to PDF pages',
    icon: '🔏',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    category: 'security',
    apiEndpoint: '/pdf/stamp',
    multipleFiles: false,
    inputLabel: 'Select PDF to stamp',
    acceptedFormats: '.pdf',
    outputFormat: 'stamped.pdf',
    outputMime: 'application/pdf',
    params: [
      { name: 'text', label: 'Stamp Text', type: 'text', defaultValue: 'APPROVED', placeholder: 'APPROVED, DRAFT, VOID…' },
      {
        name: 'position',
        label: 'Position',
        type: 'select',
        options: [
          { value: 'center',       label: 'Center'       },
          { value: 'top-left',     label: 'Top Left'     },
          { value: 'top-right',    label: 'Top Right'    },
          { value: 'bottom-left',  label: 'Bottom Left'  },
          { value: 'bottom-right', label: 'Bottom Right' },
        ],
        defaultValue: 'center',
      },
      { name: 'pages',     label: 'Apply to Pages (all or e.g. 1-3)', type: 'text',   defaultValue: 'all' },
      { name: 'font_size', label: 'Font Size',                         type: 'number', defaultValue: 48 },
      { name: 'color',     label: 'Stamp Color',                       type: 'color',  defaultValue: '#ff0000' },
      { name: 'opacity',   label: 'Opacity (0–100)',                   type: 'number', defaultValue: 40 },
      { name: 'rotation',  label: 'Rotation (degrees)',                type: 'number', defaultValue: 330 },
    ],
    seoTitle: 'Free PDF Stamp Tool | Add Stamp Online',
    seoDescription: 'Use our free PDF stamp tool to add stamps to PDF instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'digital-id',
    name: 'Digital ID',
    description: 'Create a digital identity certificate for PDF document signing',
    icon: '🪪',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    category: 'security',
    apiEndpoint: '/pdf/digital-id',
    multipleFiles: false,
    fileOptional: true,
    inputLabel: 'Select PDF to attach digital ID to (optional)',
    acceptedFormats: '.pdf',
    outputFormat: 'digital-id.p12',
    outputMime: 'application/x-pkcs12',
    params: [
      { name: 'name',         label: 'Full Name',     type: 'text', defaultValue: '', placeholder: 'Your full name' },
      { name: 'organization', label: 'Organization',  type: 'text', defaultValue: '', placeholder: 'Company name'  },
      { name: 'email',        label: 'Email Address', type: 'text', defaultValue: '', placeholder: 'email@example.com' },
    ],
    seoTitle: 'Free Digital ID Tool | Create Digital ID Online',
    seoDescription: 'Use our free digital ID tool to create and manage digital IDs instantly online. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'validate-signature',
    name: 'Validate Signature',
    description: 'Check digital signatures and perform revocation checks on a signed PDF',
    icon: '✔️',
    color: '#ef4444',
    bgColor: '#fef2f2',
    borderColor: '#fecaca',
    category: 'security',
    apiEndpoint: '/pdf/validate-signature',
    multipleFiles: false,
    inputLabel: 'Select signed PDF to validate',
    acceptedFormats: '.pdf',
    outputFormat: 'validation.json',
    outputMime: 'application/json',
    seoTitle: 'Free Validate Signature Tool | Check PDF Signatures',
    seoDescription: 'Use our free signature validation tool to verify PDF signatures instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  // ─── Interactive Forms ─────────────────────────────────────────────────────
  {
    slug: 'create-form',
    name: 'Create Form',
    description: 'Add interactive text fields, checkboxes, dropdowns, and radio buttons to a PDF',
    icon: '📋',
    color: '#7c3aed',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'forms',
    apiEndpoint: '/pdf/create-form',
    multipleFiles: false,
    inputLabel: 'Select PDF to add form fields to',
    acceptedFormats: '.pdf',
    outputFormat: 'form.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'fields',
        label: 'Fields (JSON array)',
        type: 'text',
        placeholder: '[{"type":"text","name":"full_name","label":"Full Name","page":1,"x":100,"y":700,"width":200,"height":24},{"type":"checkbox","name":"agree","label":"I Agree","page":1,"x":100,"y":660}]',
      },
    ],
    seoTitle: 'Free Online Form Builder | Create Forms Easily',
    seoDescription: 'Use our free form builder to create online forms instantly. Fast, easy, and 100% online — no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'fill-form',
    name: 'Fill Form',
    description: 'Populate existing PDF form fields programmatically with provided values',
    icon: '✍️',
    color: '#7c3aed',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'forms',
    apiEndpoint: '/pdf/fill-form',
    multipleFiles: false,
    inputLabel: 'Select PDF form to fill',
    acceptedFormats: '.pdf',
    outputFormat: 'filled.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'data',
        label: 'Field values (JSON object)',
        type: 'text',
        placeholder: '{"full_name":"Jane Doe","agree":true,"country":"US"}',
      },
      {
        name: 'flatten',
        label: 'Flatten after filling',
        type: 'select',
        options: [
          { value: 'false', label: 'Keep fields editable' },
          { value: 'true',  label: 'Flatten (non-editable)' },
        ],
        defaultValue: 'false',
      },
    ],
    seoTitle: 'Free Fill Form Tool | Fill Forms Online',
    seoDescription: 'Use our free fill form tool to complete online forms instantly. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'export-form-data',
    name: 'Export Form Data',
    description: 'Extract filled form field values from a PDF and export as JSON or CSV',
    icon: '📤',
    color: '#7c3aed',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'forms',
    apiEndpoint: '/pdf/export-form-data',
    multipleFiles: false,
    inputLabel: 'Select filled PDF form',
    acceptedFormats: '.pdf',
    outputFormat: 'form-data.json',
    outputMime: 'application/json',
    params: [
      {
        name: 'format',
        label: 'Export format',
        type: 'select',
        options: [
          { value: 'json', label: 'JSON' },
          { value: 'csv',  label: 'CSV'  },
        ],
        defaultValue: 'json',
      },
    ],
    seoTitle: 'Free Export Form Data Tool | Extract Form Data Online',
    seoDescription: 'Use our free export form data tool to extract and download form data instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'validate-form',
    name: 'Validate Form',
    description: 'Check that all required form fields in a PDF are filled and report any missing values',
    icon: '🔍',
    color: '#7c3aed',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'forms',
    apiEndpoint: '/pdf/validate-form',
    multipleFiles: false,
    inputLabel: 'Select PDF form to validate',
    acceptedFormats: '.pdf',
    outputFormat: 'validation.json',
    outputMime: 'application/json',
    seoTitle: 'Free Form Validator Tool | Validate Forms Online',
    seoDescription: 'Use our free form validation tool to check and validate forms instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  {
    slug: 'form-field-management',
    name: 'Field Management',
    description: 'List, rename, reorder, or remove existing form fields in a PDF',
    icon: '🗂️',
    color: '#7c3aed',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'forms',
    apiEndpoint: '/pdf/form-field-management',
    multipleFiles: false,
    inputLabel: 'Select PDF with form fields',
    acceptedFormats: '.pdf',
    outputFormat: 'managed.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { value: 'list',   label: 'List all fields' },
          { value: 'remove', label: 'Remove field by name' },
          { value: 'rename', label: 'Rename field' },
        ],
        defaultValue: 'list',
      },
      { name: 'field_name',     label: 'Field name',         type: 'text', placeholder: 'full_name' },
      { name: 'new_field_name', label: 'New name (rename)',  type: 'text', placeholder: 'full_name_updated' },
    ],
    seoTitle: 'Free Form Field Management Tool | Edit Forms Online',
    seoDescription: 'Use our free form field management tool to edit and manage form fields instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },

  // ─── Technical Standards ───────────────────────────────────────────────────
  {
    slug: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Convert PDF to PDF/A format for long-term archiving',
    icon: '🏛️',
    color: '#eab308',
    bgColor: '#fefce8',
    borderColor: '#fef08a',
    category: 'standards',
    apiEndpoint: '/pdf/pdf-to-pdfa',
    multipleFiles: false,
    inputLabel: 'Select PDF to archive',
    acceptedFormats: '.pdf',
    outputFormat: 'converted_pdfa.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free PDF to PDF/A Tool | Convert PDF Online',
    seoDescription: 'Use our free PDF to PDF/A tool to convert PDF files into PDF/A format instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
  {
    slug: 'validate-pdfa',
    name: 'Validate PDF/A',
    description: 'Check whether a PDF file is valid PDF/A compliant',
    icon: '✅',
    color: '#eab308',
    bgColor: '#fefce8',
    borderColor: '#fef08a',
    category: 'standards',
    apiEndpoint: '/pdf/validate-pdfa',
    multipleFiles: false,
    inputLabel: 'Select PDF to validate',
    acceptedFormats: '.pdf',
    outputFormat: 'validation.json',
    outputMime: 'application/json',
    seoTitle: 'Free PDF/A Validator Tool | Check PDF/A Online',
    seoDescription: 'Use our free PDF/A validator tool to check PDF/A compliance instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'pdf-to-pdfx',
    name: 'PDF to PDF/X',
    description: 'Convert PDF to PDF/X format for professional print production and prepress workflows',
    icon: '🖨️',
    color: '#eab308',
    bgColor: '#fefce8',
    borderColor: '#fef08a',
    category: 'standards',
    apiEndpoint: '/pdf/pdf-to-pdfx',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted_pdfx.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'variant',
        label: 'PDF/X variant',
        type: 'select',
        options: [
          { value: 'PDF/X-1a', label: 'PDF/X-1a (CMYK, no transparency)' },
          { value: 'PDF/X-3',  label: 'PDF/X-3  (color-managed)'         },
          { value: 'PDF/X-4',  label: 'PDF/X-4  (transparency allowed)'  },
        ],
        defaultValue: 'PDF/X-1a',
      },
    ],
    seoTitle: 'Free PDF to PDF/X Tool | Convert PDF Online',
    seoDescription: 'Use our free PDF to PDF/X tool to convert PDF files instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'pdf-to-pdfe',
    name: 'PDF to PDF/E',
    description: 'Convert PDF to PDF/E format for engineering and technical document exchange',
    icon: '⚙️',
    color: '#eab308',
    bgColor: '#fefce8',
    borderColor: '#fef08a',
    category: 'standards',
    apiEndpoint: '/pdf/pdf-to-pdfe',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted_pdfe.pdf',
    outputMime: 'application/pdf',
    seoTitle: 'Free PDF to PDF/E Tool | Convert PDF Online',
    seoDescription: 'Use our free PDF to PDF/E tool to convert PDF files instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'pdf-to-pdfua',
    name: 'PDF to PDF/UA',
    description: 'Convert PDF to PDF/UA (Universal Accessibility) format for assistive-technology compatibility',
    icon: '♿',
    color: '#eab308',
    bgColor: '#fefce8',
    borderColor: '#fef08a',
    category: 'standards',
    apiEndpoint: '/pdf/pdf-to-pdfua',
    multipleFiles: false,
    inputLabel: 'Select PDF to convert',
    acceptedFormats: '.pdf',
    outputFormat: 'converted_pdfua.pdf',
    outputMime: 'application/pdf',
    params: [
      {
        name: 'title',
        label: 'Document title (for accessibility)',
        type: 'text',
        placeholder: 'My Document',
      },
      {
        name: 'lang',
        label: 'Language code',
        type: 'text',
        placeholder: 'en-US',
        defaultValue: 'en-US',
      },
    ],
    seoTitle: 'Free PDF to PDF/A Converter | Convert PDF to PDF/A Online',
    seoDescription: 'Use our free PDF to PDF/A tool to convert PDF files into archival PDF/A format instantly. Fast, easy, and 100% online — no installation needed.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ─── DIGITAL IMAGE HUB ────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════

  // ─── Digital Image Conversions ────────────────────────────────────────────
  {
    slug: 'jpg-jpeg-update',
    name: 'JPG/JPEG Extension Update',
    description: 'Standardize your image file extension between .jpg and .jpeg formats',
    icon: '🔄',
    color: '#8b5cf6',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'img-convert',
    apiEndpoint: '/image/jpg-jpeg-update',
    multipleFiles: false,
    inputLabel: 'Select JPG or JPEG image',
    acceptedFormats: '.jpg,.jpeg',
    outputFormat: 'updated.jpg',
    outputMime: 'image/jpeg',
    params: [
      {
        name: 'output_extension',
        label: 'Output Extension',
        type: 'select',
        options: [
          { value: 'jpg',  label: '.jpg' },
          { value: 'jpeg', label: '.jpeg' },
        ],
        defaultValue: 'jpg',
      },
    ],
    seoTitle: 'Free JPG to JPEG Update Tool | Convert Images Online',
    seoDescription: 'Use our free JPG to JPEG update tool to convert images instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'jpg-to-png',
    name: 'Convert to PNG',
    description: 'Convert JPG or JPEG images to PNG format with full transparency support',
    icon: '🖼️',
    color: '#8b5cf6',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'img-convert',
    apiEndpoint: '/image/jpg-to-png',
    multipleFiles: false,
    inputLabel: 'Select JPG/JPEG image to convert',
    acceptedFormats: '.jpg,.jpeg',
    outputFormat: 'converted.png',
    outputMime: 'image/png',
    seoTitle: 'Free JPG to PNG Tool | Convert Images Online',
    seoDescription: 'Use our free JPG to PNG tool to convert images instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'png-to-jpg',
    name: 'Convert to JPG/JPEG',
    description: 'Convert PNG images to JPG/JPEG; transparent areas become a solid background',
    icon: '📸',
    color: '#8b5cf6',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'img-convert',
    apiEndpoint: '/image/png-to-jpg',
    multipleFiles: false,
    inputLabel: 'Select PNG image to convert',
    acceptedFormats: '.png',
    outputFormat: 'converted.jpg',
    outputMime: 'image/jpeg',
    params: [
      { name: 'background_color', label: 'Background Color (replaces transparency)', type: 'color', defaultValue: '#ffffff' },
      { name: 'quality', label: 'JPEG Quality (1–100)', type: 'number', defaultValue: 90 },
    ],
    seoTitle: 'Free PNG to JPG Tool | Convert Images Online',
    seoDescription: 'Use our free PNG to JPG tool to convert PNG images to JPG instantly. Fast, easy, and 100% online — no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'html-to-image',
    name: 'HTML to Image',
    description: 'Render web code (HTML/CSS) from a URL or uploaded file into a static image',
    icon: '🌐',
    color: '#8b5cf6',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'img-convert',
    apiEndpoint: '/image/html-to-image',
    multipleFiles: false,
    fileOptional: true,
    inputLabel: 'Select HTML file (optional — provide URL instead)',
    acceptedFormats: '.html,.htm',
    outputFormat: 'screenshot.png',
    outputMime: 'image/png',
    params: [
      { name: 'url', label: 'Web Page URL (leave blank if uploading a file)', type: 'text', defaultValue: '', placeholder: 'https://example.com' },
      {
        name: 'output_format',
        label: 'Output Format',
        type: 'select',
        options: [
          { value: 'png', label: 'PNG' },
          { value: 'jpg', label: 'JPG' },
        ],
        defaultValue: 'png',
      },
      { name: 'width',  label: 'Viewport Width (px)',  type: 'number', defaultValue: 1280 },
      { name: 'height', label: 'Viewport Height (px)', type: 'number', defaultValue: 720  },
    ],
    seoTitle: 'Free HTML to Image Tool | Convert HTML Online',
    seoDescription: 'Use our free HTML to image tool to convert HTML into images instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'image-format-converter',
    name: 'Any-to-Any Converter',
    description: 'Universal image converter supporting BMP, TIFF, AVIF, GIF, SVG, HEIC, WebP and more',
    icon: '🔀',
    color: '#8b5cf6',
    bgColor: '#f5f3ff',
    borderColor: '#ddd6fe',
    category: 'img-convert',
    apiEndpoint: '/image/convert',
    multipleFiles: false,
    inputLabel: 'Select image to convert',
    acceptedFormats: '.jpg,.jpeg,.png,.bmp,.tiff,.gif,.svg,.webp,.avif,.heic,.ico',
    outputFormat: 'converted.png',
    outputMime: 'image/png',
    params: [
      {
        name: 'output_format',
        label: 'Output Format',
        type: 'select',
        options: [
          { value: 'png',  label: 'PNG'      },
          { value: 'jpg',  label: 'JPG/JPEG' },
          { value: 'bmp',  label: 'BMP'      },
          { value: 'tiff', label: 'TIFF'     },
          { value: 'avif', label: 'AVIF'     },
          { value: 'gif',  label: 'GIF'      },
          { value: 'webp', label: 'WebP'     },
          { value: 'ico',  label: 'ICO'      },
        ],
        defaultValue: 'png',
      },
    ],
    seoTitle: 'Free Image Format Converter | Convert Online',
    seoDescription: 'Use our free image format converter to change JPG, PNG, WebP instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },

  // ─── Sizing & Dimensions ───────────────────────────────────────────────────
  {
    slug: 'image-compress',
    name: 'Compress Image',
    description: 'Reduce image file size while maintaining visual quality',
    icon: '🗜️',
    color: '#14b8a6',
    bgColor: '#f0fdfa',
    borderColor: '#99f6e4',
    category: 'img-size',
    apiEndpoint: '/image/compress',
    multipleFiles: false,
    inputLabel: 'Select image to compress',
    acceptedFormats: '.jpg,.jpeg,.png,.webp,.bmp',
    outputFormat: 'compressed.jpg',
    outputMime: 'image/jpeg',
    params: [
      { name: 'quality', label: 'Quality (1–100)', type: 'number', defaultValue: 75 },
      {
        name: 'output_format',
        label: 'Output Format',
        type: 'select',
        options: [
          { value: 'jpg',  label: 'JPG'  },
          { value: 'png',  label: 'PNG'  },
          { value: 'webp', label: 'WebP' },
        ],
        defaultValue: 'jpg',
      },
    ],
    seoTitle: 'Free Image Compress Tool | Compress Images Online',
    seoDescription: 'Use our free image compress tool to reduce image size instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'image-resize',
    name: 'Resize Image',
    description: 'Change image pixel dimensions with flexible fit and aspect ratio options',
    icon: '↔️',
    color: '#14b8a6',
    bgColor: '#f0fdfa',
    borderColor: '#99f6e4',
    category: 'img-size',
    apiEndpoint: '/image/resize',
    multipleFiles: false,
    inputLabel: 'Select image to resize',
    acceptedFormats: '.jpg,.jpeg,.png,.webp,.bmp,.gif,.tiff',
    outputFormat: 'resized.jpg',
    outputMime: 'image/jpeg',
    params: [
      { name: 'width',  label: 'Width (px)',  type: 'number', defaultValue: 800 },
      { name: 'height', label: 'Height (px)', type: 'number', defaultValue: 600 },
      {
        name: 'fit',
        label: 'Resize Mode',
        type: 'select',
        options: [
          { value: 'cover',   label: 'Cover (crop to fill)'  },
          { value: 'contain', label: 'Contain (fit within)'  },
          { value: 'fill',    label: 'Fill (stretch)'        },
          { value: 'inside',  label: 'Inside (scale down only)' },
          { value: 'outside', label: 'Outside (scale up only)'  },
        ],
        defaultValue: 'cover',
      },
    ],
    seoTitle: 'Free Image Resize Tool | Resize Images Online',
    seoDescription: 'Use our free image resize tool to resize images instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'image-crop',
    name: 'Crop Image',
    description: 'Remove outer areas of an image to adjust focus and composition',
    icon: '✂️',
    color: '#14b8a6',
    bgColor: '#f0fdfa',
    borderColor: '#99f6e4',
    category: 'img-size',
    apiEndpoint: '/image/crop',
    multipleFiles: false,
    inputLabel: 'Select image to crop',
    acceptedFormats: '.jpg,.jpeg,.png,.webp,.bmp,.gif,.tiff',
    outputFormat: 'cropped.jpg',
    outputMime: 'image/jpeg',
    params: [
      { name: 'x',      label: 'Left Offset (px)',  type: 'number', defaultValue: 0   },
      { name: 'y',      label: 'Top Offset (px)',   type: 'number', defaultValue: 0   },
      { name: 'width',  label: 'Crop Width (px)',   type: 'number', defaultValue: 800 },
      { name: 'height', label: 'Crop Height (px)',  type: 'number', defaultValue: 600 },
    ],
    seoTitle: 'Free Image Crop Tool | Crop Images Online',
    seoDescription: 'Use our image crop tool to crop images instantly online. Fast, easy, and free browser-based solution for resizing and editing photos. Try it now',
  },

  // ─── Image Enhancements ────────────────────────────────────────────────────
  {
    slug: 'ai-upscale',
    name: 'AI Upscaling',
    description: 'Use AI to increase image resolution and enhance fine details up to 4×',
    icon: '🔬',
    color: '#f59e0b',
    bgColor: '#fffbeb',
    borderColor: '#fde68a',
    category: 'img-enhance',
    apiEndpoint: '/image/ai-upscale',
    multipleFiles: false,
    inputLabel: 'Select image to upscale',
    acceptedFormats: '.jpg,.jpeg,.png,.webp',
    outputFormat: 'upscaled.png',
    outputMime: 'image/png',
    params: [
      {
        name: 'scale',
        label: 'Upscale Factor',
        type: 'select',
        options: [
          { value: '2', label: '2× (Double resolution)'     },
          { value: '4', label: '4× (Quadruple resolution)'  },
        ],
        defaultValue: '2',
      },
    ],
    seoTitle: 'Free AI Upscale Tool | Enhance Images Online',
    seoDescription: 'Use our free AI upscale tool to enhance and upscale images instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'image-unblur',
    name: 'Unblur Image',
    description: 'Sharpen and improve clarity of blurry or out-of-focus images',
    icon: '🔍',
    color: '#f59e0b',
    bgColor: '#fffbeb',
    borderColor: '#fde68a',
    category: 'img-enhance',
    apiEndpoint: '/image/unblur',
    multipleFiles: false,
    inputLabel: 'Select blurry image to sharpen',
    acceptedFormats: '.jpg,.jpeg,.png,.webp',
    outputFormat: 'sharpened.jpg',
    outputMime: 'image/jpeg',
    params: [
      { name: 'strength', label: 'Sharpening Strength (1–10)', type: 'number', defaultValue: 5 },
    ],
    seoTitle: 'Free Image Unblur Tool | Sharpen Blurry Images Online',
    seoDescription: 'Use our free image unblur tool to sharpen and restore blurry images instantly. Fast, easy, and 100% online — no installation needed. Try GoDocLab now!',
  },

  // ─── Visual Effects ────────────────────────────────────────────────────────
  {
    slug: 'image-blur',
    name: 'Blur Image',
    description: 'Apply blur effect to obscure sensitive details or create artistic background effects',
    icon: '💫',
    color: '#ec4899',
    bgColor: '#fdf2f8',
    borderColor: '#fbcfe8',
    category: 'img-effects',
    apiEndpoint: '/image/blur',
    multipleFiles: false,
    inputLabel: 'Select image to blur',
    acceptedFormats: '.jpg,.jpeg,.png,.webp,.bmp',
    outputFormat: 'blurred.jpg',
    outputMime: 'image/jpeg',
    params: [
      { name: 'radius', label: 'Blur Radius (1–50)', type: 'number', defaultValue: 10 },
      {
        name: 'blur_type',
        label: 'Blur Type',
        type: 'select',
        options: [
          { value: 'gaussian', label: 'Gaussian Blur' },
          { value: 'motion',   label: 'Motion Blur'   },
          { value: 'box',      label: 'Box Blur'      },
        ],
        defaultValue: 'gaussian',
      },
    ],
    seoTitle: 'Free Image Blur Tool | Blur Images Online',
    seoDescription: 'Use our free image blur tool to blur images instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'image-rotate',
    name: 'Rotate Image',
    description: 'Rotate image 90°, 180°, 270°, or to any custom angle with background fill',
    icon: '🔄',
    color: '#ec4899',
    bgColor: '#fdf2f8',
    borderColor: '#fbcfe8',
    category: 'img-effects',
    apiEndpoint: '/image/rotate',
    multipleFiles: false,
    inputLabel: 'Select image to rotate',
    acceptedFormats: '.jpg,.jpeg,.png,.webp,.bmp,.gif,.tiff',
    outputFormat: 'rotated.jpg',
    outputMime: 'image/jpeg',
    params: [
      {
        name: 'angle',
        label: 'Rotation Angle',
        type: 'select',
        options: [
          { value: '90',     label: '90° Clockwise'              },
          { value: '180',    label: '180°'                       },
          { value: '270',    label: '270° (90° Counter-clockwise)' },
          { value: 'custom', label: 'Custom Angle'               },
        ],
        defaultValue: '90',
      },
      { name: 'custom_angle', label: 'Custom Angle (0–360°)', type: 'number', defaultValue: 45 },
      { name: 'background',   label: 'Background Fill Color',  type: 'color',  defaultValue: '#ffffff' },
    ],
    seoTitle: 'Free Image Rotate Tool | Rotate Images Online',
    seoDescription: 'Use our free image rotate tool to rotate images instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'image-tilt-flip',
    name: 'Tilt & Flip',
    description: 'Apply a custom tilt and flip images horizontally, vertically, or both',
    icon: '↕️',
    color: '#ec4899',
    bgColor: '#fdf2f8',
    borderColor: '#fbcfe8',
    category: 'img-effects',
    apiEndpoint: '/image/tilt-flip',
    multipleFiles: false,
    inputLabel: 'Select image to tilt or flip',
    acceptedFormats: '.jpg,.jpeg,.png,.webp,.bmp,.gif',
    outputFormat: 'flipped.jpg',
    outputMime: 'image/jpeg',
    params: [
      {
        name: 'flip',
        label: 'Flip Direction',
        type: 'select',
        options: [
          { value: 'none',       label: 'No Flip'               },
          { value: 'horizontal', label: 'Horizontal (Mirror)'   },
          { value: 'vertical',   label: 'Vertical (Upside Down)' },
          { value: 'both',       label: 'Both'                  },
        ],
        defaultValue: 'horizontal',
      },
      { name: 'tilt',       label: 'Tilt Angle (-45° to 45°)', type: 'number', defaultValue: 0 },
      { name: 'background', label: 'Background Fill Color',     type: 'color',  defaultValue: '#ffffff' },
    ],
    seoTitle: 'Free Image Tilt Flip Tool | Rotate Images Online',
    seoDescription: 'Use our free image tilt flip tool to rotate and flip images instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },

  // ─── Image Content Editing ─────────────────────────────────────────────────
  {
    slug: 'remove-background',
    name: 'Remove Background',
    description: 'Automatically isolate the main subject by removing the image background',
    icon: '🪄',
    color: '#6366f1',
    bgColor: '#eef2ff',
    borderColor: '#c7d2fe',
    category: 'img-edit',
    apiEndpoint: '/image/remove-background',
    multipleFiles: false,
    inputLabel: 'Select image to process',
    acceptedFormats: '.jpg,.jpeg,.png,.webp',
    outputFormat: 'nobg.png',
    outputMime: 'image/png',
    seoTitle: 'Free Remove Background Tool | Erase Image Background Online',
    seoDescription: 'Use our free remove background tool to erase image backgrounds instantly online. Fast, easy, and 100% online — no installation needed.',
  },
  {
    slug: 'image-add-watermark',
    name: 'Image Watermark',
    description: 'Add a text or logo watermark for branding and content protection',
    icon: '💧',
    color: '#6366f1',
    bgColor: '#eef2ff',
    borderColor: '#c7d2fe',
    category: 'img-edit',
    apiEndpoint: '/image/watermark',
    multipleFiles: false,
    inputLabel: 'Select image to watermark',
    acceptedFormats: '.jpg,.jpeg,.png,.webp',
    outputFormat: 'watermarked.jpg',
    outputMime: 'image/jpeg',
    params: [
      { name: 'text', label: 'Watermark Text', type: 'text', defaultValue: '© My Brand', placeholder: 'Enter watermark text' },
      {
        name: 'position',
        label: 'Position',
        type: 'select',
        options: [
          { value: 'center',       label: 'Center'       },
          { value: 'top-left',     label: 'Top Left'     },
          { value: 'top-right',    label: 'Top Right'    },
          { value: 'bottom-left',  label: 'Bottom Left'  },
          { value: 'bottom-right', label: 'Bottom Right' },
        ],
        defaultValue: 'bottom-right',
      },
      { name: 'font_size', label: 'Font Size',       type: 'number', defaultValue: 24 },
      { name: 'opacity',   label: 'Opacity (0–100)', type: 'number', defaultValue: 60 },
      { name: 'color',     label: 'Text Color',      type: 'color',  defaultValue: '#ffffff' },
      { name: 'rotation',  label: 'Rotation (°)',    type: 'number', defaultValue: 0 },
    ],
    seoTitle: 'Free Image Watermark Tool | Add Logo Online Fast',
    seoDescription: 'Use image add watermark tool to add text or logo watermarks online in seconds. Fast, easy, free and fully online — no installation needed at all.',
  },
  {
    slug: 'meme-generator',
    name: 'Meme Generator',
    description: 'Add bold stylized top and bottom text to create memes from any image',
    icon: '😄',
    color: '#6366f1',
    bgColor: '#eef2ff',
    borderColor: '#c7d2fe',
    category: 'img-edit',
    apiEndpoint: '/image/meme',
    multipleFiles: false,
    inputLabel: 'Select meme template image',
    acceptedFormats: '.jpg,.jpeg,.png,.webp',
    outputFormat: 'meme.jpg',
    outputMime: 'image/jpeg',
    params: [
      { name: 'top_text',    label: 'Top Text',            type: 'text',   defaultValue: '',        placeholder: 'Top caption text'    },
      { name: 'bottom_text', label: 'Bottom Text',         type: 'text',   defaultValue: '',        placeholder: 'Bottom caption text' },
      { name: 'font_size',   label: 'Font Size',           type: 'number', defaultValue: 36                                            },
      { name: 'text_color',  label: 'Text Color',          type: 'color',  defaultValue: '#ffffff'                                     },
      { name: 'stroke_color',label: 'Outline/Stroke Color',type: 'color',  defaultValue: '#000000'                                     },
    ],
    seoTitle: 'Free Meme Generator Tool | Create Memes Online',
    seoDescription: 'Use our free meme generator tool to create memes instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab now!',
  },
  {
    slug: 'photo-editor',
    name: 'Photo Editor',
    description: 'Full suite editor: adjust brightness, contrast, saturation, and apply artistic filters',
    icon: '🎨',
    color: '#6366f1',
    bgColor: '#eef2ff',
    borderColor: '#c7d2fe',
    category: 'img-edit',
    apiEndpoint: '/image/photo-editor',
    multipleFiles: false,
    inputLabel: 'Select image to edit',
    acceptedFormats: '.jpg,.jpeg,.png,.webp,.bmp',
    outputFormat: 'edited.jpg',
    outputMime: 'image/jpeg',
    params: [
      { name: 'brightness', label: 'Brightness (-100 to 100)', type: 'number', defaultValue: 0 },
      { name: 'contrast',   label: 'Contrast (-100 to 100)',   type: 'number', defaultValue: 0 },
      { name: 'saturation', label: 'Saturation (-100 to 100)', type: 'number', defaultValue: 0 },
      { name: 'hue',        label: 'Hue Rotation (degrees)',   type: 'number', defaultValue: 0 },
      { name: 'sharpness',  label: 'Sharpness (0–10)',         type: 'number', defaultValue: 0 },
      {
        name: 'filter',
        label: 'Artistic Filter',
        type: 'select',
        options: [
          { value: 'none',      label: 'None'      },
          { value: 'grayscale', label: 'Grayscale' },
          { value: 'sepia',     label: 'Sepia'     },
          { value: 'invert',    label: 'Invert'    },
          { value: 'vintage',   label: 'Vintage'   },
          { value: 'vivid',     label: 'Vivid'     },
          { value: 'cool',      label: 'Cool Tone' },
          { value: 'warm',      label: 'Warm Tone' },
        ],
        defaultValue: 'none',
      },
    ],
    seoTitle: 'Free Photo Editor | Edit Images Online',
    seoDescription: 'Use our free photo editor to edit images instantly online. Fast, easy, and 100% web-based—no installation needed. Try GoDocLab now for free!',
  },
  // ─── Watermark Removal ────────────────────────────────────────────────────
  {
    slug: 'remove-watermark',
    name: 'Remove Watermark',
    description: 'Remove semi-transparent watermarks and overlay text from images',
    icon: '🧹',
    color: '#6366f1',
    bgColor: '#eef2ff',
    borderColor: '#c7d2fe',
    category: 'img-edit',
    apiEndpoint: '/image/remove-watermark',
    multipleFiles: false,
    inputLabel: 'Select image to clean',
    acceptedFormats: '.jpg,.jpeg,.png,.webp',
    outputFormat: 'cleaned.jpg',
    outputMime: 'image/jpeg',
    params: [
      {
        name: 'strength',
        label: 'Removal Strength',
        type: 'select',
        options: [
          { value: '30', label: 'Light (30%) — subtle overlays' },
          { value: '60', label: 'Medium (60%) — standard watermarks' },
          { value: '85', label: 'Strong (85%) — heavy watermarks' },
        ],
        defaultValue: '60',
      },
    ],
    seoTitle: 'Free Remove Watermark Tool | Delete Watermarks Online',
    seoDescription: 'Use our free remove watermark tool to delete watermarks from images instantly online. Fast, easy, and 100% free—no installation needed. Try GoDocLab!',
  },
];
